export default [
  {
    isBlurred: false,
    title: 'Programming and Computer Science Foundation',
    subTitle: 'Core Level 1',
    tags: [
      'C Language',
      'Python',
      'SQL',
      'Command Line',
      'HTML',
      'CSS',
      'JavaScript',
      'CSS',
      'HTML',
    ],
    description:
      'You will learn how to think algorithmically and solve problems efficiently. You will go through topics like abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering and web development. Languages you learn include C, Python, SQL, and JavaScript plus CSS and HTML',
    detailsLink: '/programming-and-computer-science-foundation',
  },
  {
    isBlurred: true,
    title: 'Advanced Algorithms and Problem Solving',
    subTitle: 'Core Level 2',
    tags: [
      'C Language',
      'Python',
      'SQL',
      'Command Line',
      'HTML',
      'CSS',
      'JavaScript',
      'CSS',
      'HTML',
    ],
    description:
      'Every serious programmer should know Data Structures and Algorithms. You will learn how to think algorithmically and solve problems efficiently. This also lays strong foundation for problem solving skills and Software Engineering interviews. You learn how slove problems using Data Strutures and Algorithms',
    detailsLink: '',
  },
  {
    isBlurred: true,
    title: 'Cracking Coding Interviews',
    subTitle: 'Core Level 3',
    tags: [
      'C Language',
      'Python',
      'SQL',
      'Command Line',
      'HTML',
      'CSS',
      'JavaScript',
      'CSS',
      'HTML',
    ],
    description:
      'Every serious programmer should know Data Structures and Algorithms. You will learn how to think algorithmically and solve problems efficiently. This also lays strong foundation for problem solving skills and Software Engineering interviews. You learn how slove problems using Data Strutures and Algorithms',
    detailsLink: '',
  },
  {
    isBlurred: true,
    title: 'Web Development (Node & React)',
    subTitle: 'Software Development',
    tags: [
      'Javascript',
      'Node.js',
      'SQL',
      'Command Line',
      'HTML',
      'CSS',
      'SASS',
      'React',
      'Redux',
    ],
    description:
      'Every serious programmer should know Data Structures and Algorithms. You will learn how to think algorithmically and solve problems efficiently. This also lays strong foundation for problem solving skills and Software Engineering interviews. You learn how slove problems using Data Strutures and Algorithms',
    detailsLink: '',
  },
  {
    isBlurred: true,
    title: 'Web Development (Python & JavaScript)',
    subTitle: 'Software Development',
    tags: [
      'C Language',
      'Python',
      'SQL',
      'Command Line',
      'HTML',
      'CSS',
      'JavaScript',
      'CSS',
      'HTML',
    ],
    description:
      'Every serious programmer should know Data Structures and Algorithms. You will learn how to think algorithmically and solve problems efficiently. This also lays strong foundation for problem solving skills and Software Engineering interviews. You learn how slove problems using Data Strutures and Algorithms',
    detailsLink: '',
  },
];
